resolver: lts-21.24
packages:
- .
extra-deps:
- git: https://github.com/syallop/PLLabel
  commit: d0f17cf627c28e005d02e13a69a74ccd615cc9d1
- git: https://github.com/syallop/PLPrinter
  commit: 74fd1a684542f9f876753e2d7b3b0d5609bf385e
flags: {}
extra-package-dbs: []

